apiVersion: apps/v1
kind: Deployment
metadata:
  name: fheta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fheta
  template:
    metadata:
      labels:
        app: fheta
    spec:
      containers:
      - image: okteto.dev/fheta:latest
        name: fheta
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "96e406b9-283d-4024-aeda-33a91087cca1"
        - name: Vless_Path
          value: "/vlfgjer532"
        - name: Vmess_UUID
          value: "96e406b9-283d-4024-aeda-33a91087cca1"
        - name: Vmess_Path
          value: "/vmyu5634"
        - name: Share_Path
          value: "/v2link"
